// Build window.testData exclusively from window.addedImports (generated by last403_explanations_import.js)
// LAST403 ONLY MODE builder
(function(){
  try {
    const imports = Array.isArray(window.addedImports) ? window.addedImports : [];
    if (!imports.length) {
      console.warn('[last403-only] No imports found in window.addedImports');
    }
    const data = {};

    const prettyName = (key) => {
      const map = {
        'air-law': 'Air Law',
        'aircraft-general': 'Aircraft General Knowledge',
        'aon-aviation': 'AON Aviation'
      };
      if (map[key]) return map[key];
      return String(key || 'Misc')
        .replace(/[-_]+/g,' ')
        .replace(/\b\w/g, c => c.toUpperCase());
    };

    const slug = (s) => String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

    for (const catImp of imports) {
      const key = catImp.category || 'misc';
      if (!data[key]) {
        data[key] = { name: prettyName(key), icon: 'fas fa-book', tests: [] };
      }
      const cat = data[key];
      const tests = Array.isArray(catImp.tests) ? catImp.tests : [];
      tests.forEach((t, ti) => {
        const tName = (t && t.name) ? String(t.name) : `Test ${ti+1}`;
        const testId = `${key}-${slug(tName)||('test-'+(ti+1))}`;
        const timeLimit = (t && t.timeLimit) ? t.timeLimit : 60;
        const questions = (t && Array.isArray(t.questions)) ? t.questions : [];
        const normQs = questions
          .filter(q => q && q.question && Array.isArray(q.options) && q.options.length >= 2)
          .map((q, qi) => {
            const opts = q.options.map(o => String(o||'').trim()).filter(Boolean);
            let correct = (typeof q.correct === 'number') ? q.correct : 0;
            if (q.answer) {
              correct = opts.indexOf(q.answer);
              if (correct === -1) correct = 0;
            }
            if (correct < 0 || correct >= opts.length) correct = 0;
            return {
              id: `${testId}-q${qi+1}`,
              question: String(q.question).trim(),
              options: opts,
              correct,
              explanation: q.explanation ? String(q.explanation).trim() : ''
            };
          });
        cat.tests.push({ id: testId, name: tName, timeLimit, questions: normQs });
      });
    }

    // Overwrite global dataset with ONLY the imported content
    window.testData = data;

    // Dynamically (re)build category cards if container present
    try {
      const container = document.querySelector('.test-categories');
      if (container) {
        container.innerHTML = Object.entries(window.testData).map(([key, cat]) => {
          const testCount = (cat.tests||[]).length;
          const questionCount = (cat.tests||[]).reduce((a,t)=>a + (t.questions||[]).length,0);
          return `
            <div class="category-card" data-category="${key}">
              <div class="category-icon"><i class="${cat.icon||'fas fa-book'}"></i></div>
              <h3>${cat.name}</h3>
              <p>Questions sourced exclusively from LAST403 import.</p>
              <div class="category-info">
                <span class="test-count"><i class="fas fa-clipboard-list"></i> ${testCount} ${testCount===1?'Test':'Tests'}</span>
                <span class="question-count"><i class="fas fa-question-circle"></i> ${questionCount} ${questionCount===1?'Question':'Questions'}</span>
              </div>
              <button class="start-btn" data-start-category="${key}">Start</button>
            </div>`;
        }).join('');
        // Attach handlers for start buttons
        container.querySelectorAll('[data-start-category]').forEach(btn => {
          btn.addEventListener('click', (e) => {
            const catKey = e.currentTarget.getAttribute('data-start-category');
            try {
              if (window.app && typeof window.app.startTest === 'function') {
                const firstTest = (window.testData[catKey]?.tests||[])[0];
                if (firstTest) window.app.startTest(catKey, firstTest);
              }
            } catch (err) { console.warn('Failed to start test for', catKey, err); }
          });
        });
      }
    } catch (e) { console.warn('Category card rebuild failed', e); }

    // Trigger any consumers that rely on testData being ready
    try {
      if (window.app && typeof window.app.rebuildSearchEngine === 'function') {
        window.app.rebuildSearchEngine();
      }
    } catch {}
    console.log('[last403-only] Dataset built. Categories:', Object.keys(window.testData));
  } catch (e) {
    console.error('Failed to build data from last403 import:', e);
  }
})();
